# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Shopify SDK Build Feature/Hotfix Branch

on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]
    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn clean install
